[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

# RPC endpoints
[rpc_endpoints]
base = "https://mainnet.base.org"
base_testnet = "https://sepolia.base.org"
local = "http://localhost:8545"

# Etherscan API keys
[etherscan]
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Gas settings
[profile.default.gas]
gas_price = 1000000000  # 1 gwei
gas_limit = 10000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
